services:
  planetmint-1:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-1:/home/ubuntu/.planetmint-go:rw
    networks:
      - rddl
    command: planetmint-god start

  planetmint-2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-2:/home/ubuntu/.planetmint-go:rw
    networks:
      - rddl
    command: planetmint-god start
  
  planetmint-3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-3:/home/ubuntu/.planetmint-go:rw
    networks:
      - rddl
    command: planetmint-god start

  planetmint-4:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-4:/home/ubuntu/.planetmint-go:rw
    networks:
      - rddl
    command: planetmint-god start

networks:
  rddl: {}
